//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая_ПИТПМ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int Id { get; set; }
        public Nullable<int> WorkExperients { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
