//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая_ПИТПМ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Client = new HashSet<Client>();
            this.Rating = new HashSet<Rating>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public string MovieName { get; set; }
        public string MovieCountry { get; set; }
        public string MovieCategory { get; set; }
        public string MovieProducer { get; set; }
        public Nullable<int> ReleaseDate { get; set; }
        public byte[] PosterPreview { get; set; }
        public byte[] Preview { get; set; }
        public int PosterId { get; set; }
        public string Descriprion { get; set; }
        public string MovieURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual Poster Poster { get; set; }
    }
}
