//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая_ПИТПМ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int Id { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> IsBought { get; set; }
        public int ClientId { get; set; }
        public int PosterId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Poster Poster { get; set; }
    }
}
